# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'bookshelf' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bookshelf

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native'

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'Firebase/Storage', '~> 5.15.0'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  
  target 'bookshelfTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'bookshelf-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bookshelf-tvOS

  target 'bookshelf-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
