export const cities = {
  "Amman":[
    "Abdali",
    "Abdoun",
    "Abdoun Al Shamali",
    "Abu Al Qram",
    "Abu Alanda",
    "Abu Alia",
    "Abu Nsier",
    "Abu Swanah",
    "Al Abrar",
    "Al Adlyeh",
    "Al Akhdar",
    "Al Amal",
    "Al Ameer Al Hussien Bin Abdullah",
    "Al Amir Hamza",
    "Al Amir Hassan",
    "Al Amira Alia",
    "Al Andalus",
    "Al Ashrafieh",
    "Al Awdah",
    "Al Baladeyeh- Al Jubieha",
    "Al Baraka",
    "Al Bayader",
    "Al Bunayyat Al Janobi",
    "Al Bunayyat Al Shamali",
    "Al Dameneh",
    "Al Diyar",
    "Al Feisal",
    "Al Fuhais",
    "AL Furqan",
    "Al Ghaba",
    "Al Ghrous",
    "Al Hashmi Al Janobi",
    "Al Hashmi Al Shamali",
    "Al Hidayeh",
    "Al Hilal",
    "Al Hummar",
    "Al Humranyah",
    "Al Hurryeh",
    "Al Husnyeh",
    "Al Ihsan",
    "Al Iman",
    "Al Jandaweel",
    "Al Jurn",
    "Al Jwideh",
    "Al Kamaliya",
    "Al Karamah",
    "Al Khazneh",
    "Al Kom Al Gharbi",
    "Al Kom Al Sharqi",
    "Al Kuleyeh Al Islameyh - Al Juibieha",
    "Al Kursi",
    "Al Lubban",
    "Al Ma'adi",
    "Al Madinah Al Tabyeh",
    "Al Maghaba Al Sharqi",
    "Al Mahabbeh - Al Jubieha",
    "Al Majd",
    "Al Manarah",
    "Al Mansour",
    "Al Matar - Marka",
    "Al Mghaba Al Gharbi",
    "Al Morouj",
    "Al Mowahdin",
    "Al Mshairfeh",
    "Al Muqabalain",
    "Al Naharyah",
    "Al Nathif",
    "Al Oroubah",
    "Al Qasabat",
    "Al Qusour",
    "Al Qwaismeh",
    "Al Rabahieh",
    "Al Rabi",
    "Al Rabieh - Al Salam",
    "Al Rabwa",
    "Al Raqim",
    "Al Rawabi",
    "Al Rawnaq",
    "Al Rayyan - Al Jubieha",
    "Al Ridwan",
    "Al Rjoum",
    "Al Sadiq",
    "Al Safa",
    "Al Sahabah",
    "Al Sahel",
    "Al Salhien",
    "Al Shahid Al Janobi",
    "Al Shahid Al Shamali",
    "Al Sina'a",
    "Al Snobr",
    "Al Swaifyeh",
    "Al Swisah",
    "Al Thahir",
    "Al Thra'",
    "Al Tla'a Al Shamali",
    "Al Tla'a Al Sharqi",
    "Al Tunaib",
    "Al Wafa",
    "Al Yadodeh",
    "Al Zahra",
    "Al Zaytonah - Al Jubieha",
    "Al Zohour",
    "Ayn Ghazal",
    "Bilal",
    "Dabouq",
    "Daheit Al Aqsa",
    "Daheit Al Yasmeen",
    "Dahiyet Al Rashid",
    "Dhuheibah",
    "Dhuhibah Al Gharbiyah",
    "Dhuhibah Al Sharqiyah",
    "Downtown",
    "Ein Al Basha",
    "Ghamadan",
    "Hada'eq Al Hussien",
    "Hamza",
    "Hay Al Rahmanieh",
    "Hay Alkhaledeen",
    "Hettin",
    "Ibn Owf -Al Juibeiha",
    "Iraq Al Ameer",
    "Jabal Al Hussain",
    "Jabal Al Jofah",
    "Jabal Al Naser",
    "Jabal Al Nuzha",
    "Jabal Al Qala'a",
    "Jabal Al Taj",
    "Jabal Al Weibdeh",
    "Jabal Amman",
    "Jawa Al Janoubi",
    "Jawa Al Shamali",
    "Jordan Hospital Area",
    "Jubaiha",
    "Khalda",
    "Kherbat Al Souq",
    "Madinat Al Hussein",
    "Mahes",
    "Marj Al Furs",
    "Marj El Hamam",
    "Naour",
    "Qiba'a",
    "Qutnah",
    "Raghadan",
    "Ras El Ain",
    "Rujm Ashshami",
    "Safut",
    "Salem",
    "Salhyat Al Abed",
    "Shmaisani",
    "Sweileh",
    "Sweileh - Al Hai Al Sharqi",
    "Sweileh - Maisloun",
    "Tab Qira",
    "Tabarbour",
    "Taqwa",
    "The Jordan Museum Area",
    "Um El Summaq",
    "Um Hujier",
    "Um Uthainah Al Gharbi",
    "Um Uthainah Al Sharqi",
    "Umm Al Hiran",
    "Umm Al Irouq",
    "Umm Al Kundum",
    "Umm Al Usoud",
    "Umm Blaneh",
    "Umm Nowarah",
    "Umm Qusier",
    "Umm Shterat",
    "Uyun Al Dhib",
    "Wadi Al Haddadeh",
    "Wadi Al Souror",
    "Yajouz",
    "Zebda"
  ],
  "Aqaba":[
    "Al Balad Al Qadeemeh",
    "Al Herafeyeh",
    "Al Mahdood Al Gharby",
    "Al Mahdood Al Sharqy",
    "Al Mahdood Al Wasat",
    "Al Manarah",
    "Al Rimaal",
    "Al Sakaneyeh",
    "Al Shaabeyeh",
    "Al Shalalah",
    "Alhamamat Altunesyeh",
    "Sakan Al Asmedah",
    "Tala Bay",
    "Tijareyeh",
  ],
  "Irbid":[
    "Al A'awdah",
    "Al Abrar",
    "Al Afrah",
    "Al Andalus",
    "Al Ashrafiyah",
    "Al Atiba'",
    "Al Balad",
    "Al Baqa'ah",
    "Al Basatin",
    "Al Bayadah",
    "Al Fadilah",
    "Al Hashmi",
    "Al Herafyen Al Shareqi",
    "Al Hikmah",
    "Al Huson",
    "Al Iman",
    "Al Jama'ah",
    "Al Jame'",
    "Al Karama",
    "Al Lawazem",
    "Al Mala'ab",
    "Al Manara",
    "Al Marrj",
    "Al Matla'",
    "Al Maydan",
    "Al Nadif",
    "Al Nuzha",
    "Al Rahibat Al Wardiyeh",
    "Al Rawdah",
    "Al Sa'adah",
    "Al Sahel Al Akhdar",
    "Al Salam",
    "Al Sareeh",
    "Al Seha",
    "Al Senaa'ah",
    "Al Swaniyah",
    "Al Worod",
    "Al Yarmouk",
    "Al Zahra'",
    "Bait Ras",
    "Bushra",
    "Eidoon",
    "Hakama",
    "Hanina",
    "Howara",
    "Jadeed",
    "Ketem",
    "King Abdullah II Gardens",
    "Kofor Youba",
    "Mojamma' Amman Al Jadeed",
    "Mokhayam Al Shaheed",
    "University of Science and Technology"
  ],
  "Madaba":[
    "Abu Obaida",
    "Al Andalus",
    "Al Fiha'a",
    "Al Hamd",
    "Al Hashimi",
    "Al Jazira",
    "Al Karameh",
    "Al Kholafa'a",
    "Al Mokhayam",
    "Al Nasser",
    "Al Nozzha",
    "Al Sa'adeh",
    "Al Shifa'a",
    "Al Tanmiyah",
    "Al Ulama'a",
    "Al Zaytooneh",
    "Al Zohor",
    "American University",
    "Bayt Al Maqdes",
    "German University",
    "Hanina",
    "King's Academy",
    "Mahammed Al Fateh",
    "Mo'tah"
  ],
  "Salt":[
    "Al Ahlieh Uni",
    "AL Aizarieh",
    "Al Balqa Applied University",
    "Al Manshieh",
    "Al Midan",
    "Al Qala'a",
    "Al Salalem",
    "Al Salt - Balad",
    "Al Saru",
    "Wadi Al Akrad",
    "Wadi Al Halabi"
  ],
  "Zarqa":[
    "Al Ahmad",
    "Al Basatin",
    "Al Bustan",
    "AL Dobat",
    "Al Duwik",
    "Al Falah",
    "Al ghweariyyeh",
    "Al Hadiqa",
    "Al Hashemieh",
    "Al Hashmeyh Al Janobyieh",
    "Al Hashmi",
    "Al Herafien",
    "Al Jabir",
    "Al Juninah",
    "Al Madinah Al Monawarah",
    "Al Malik Talal",
    "Al mantika Al Hurra",
    "Al Masan'",
    "Al Qamar",
    "Al Shiokh",
    "Al Souq",
    "Al Tatweer Al Hadari",
    "Al Thawra Al Arabia Al Kubra",
    "Al Zarqa Al Jadeedeh",
    "Al Zawahra",
    "Awajan",
    "Barakh",
    "Dahiet Al Amera Haya",
    "Hay Al Ameer Mohammad",
    "Hay Al Hussain",
    "Hay Al Iskan",
    "Hay Al Jundi",
    "Hay Al Nuzha",
    "Hay Ma'soom",
    "Hay Ramzi",
    "Hay Shaker",
    "Ibn Sina",
    "Iskan Al Batrawi",
    "Jabal Al Abyad",
    "Jabal Al Ameer Hamza",
    "Jabal Al Ameer Hasan",
    "Jabal Al Amera Rahma",
    "Jabal Tareq",
    "Jana'a",
    "Ma'amel Al Toob",
    "Madinet El Sharq",
    "Makka Al Mokarama",
    "Nasir",
    "Nassar",
    "Prince Mohammed Stadium",
    "Qortubah",
    "Russayfa",
    "Shomar",
    "The Hashemite University",
    "Um Baiadah",
    "Zarqa Private University"
  ]
}

function citiesToDataArray(Cities) {
  let list = []
  for (let [city, areas] of Object.entries(cities)) {
    let areasList = []
    for (let area of areas) {
      areasList.push({ key: area })
    }
    list.push({ key: city, areas: areasList })
  }
  return list
}
export const citiesDataArray = citiesToDataArray(cities)